import _ from 'lodash';

import type { RawSymbol, SymbolState } from './types';

export const SYMBOL_SIZE = 105;

export const REEL_PADDING = 0.53;

// initial board (padded top and bottom)
export const INITIAL_BOARD: RawSymbol[][] = [
	[
		{ name: 'H1' },
		{ name: 'H1' },
		{ name: 'L2' },
		{ name: 'L1' },
		{ name: 'H1' },
		{ name: 'H4' },
		{ name: 'H1' },
	],
	[
		{ name: 'L3' },
		{ name: 'H2' },
		{ name: 'L1' },
		{ name: 'L2' },
		{ name: 'L1' },
		{ name: 'L2' },
		{ name: 'L2' },
	],
	[
		{ name: 'L2' },
		{ name: 'H3' },
		{ name: 'H1' },
		{ name: 'L3' },
		{ name: 'L4' },
		{ name: 'L2' },
		{ name: 'L2' },
	],
	[
		{ name: 'L3' },
		{ name: 'H4' },
		{ name: 'L3' },
		{ name: 'L4' },
		{ name: 'H4' },
		{ name: 'H1' },
		{ name: 'H1' },
	],
	[
		{ name: 'H3' },
		{ name: 'H4' },
		{ name: 'H2' },
		{ name: 'H2' },
		{ name: 'L3' },
		{ name: 'L2' },
		{ name: 'H2' },
	],
	[
		{ name: 'H2' },
		{ name: 'H2' },
		{ name: 'L1' },
		{ name: 'L3' },
		{ name: 'H1' },
		{ name: 'L1' },
		{ name: 'L2' },
	],
];

export const BOARD_DIMENSIONS = { x: INITIAL_BOARD.length, y: INITIAL_BOARD[0].length - 2 };

export const BOARD_SIZES = {
	width: SYMBOL_SIZE * BOARD_DIMENSIONS.x,
	height: SYMBOL_SIZE * BOARD_DIMENSIONS.y,
};

export const BACKGROUND_RATIO = 2039 / 1000;
export const PORTRAIT_BACKGROUND_RATIO = 1242 / 2208;
const PORTRAIT_RATIO = 800 / 1422;
const LANDSCAPE_RATIO = 1600 / 900;
const DESKTOP_RATIO = 1422 / 800;

const DESKTOP_HEIGHT = 800;
const LANDSCAPE_HEIGHT = 900;
const PORTRAIT_HEIGHT = 1422;
export const DESKTOP_MAIN_SIZES = { width: DESKTOP_HEIGHT * DESKTOP_RATIO, height: DESKTOP_HEIGHT };
export const LANDSCAPE_MAIN_SIZES = {
	width: LANDSCAPE_HEIGHT * LANDSCAPE_RATIO,
	height: LANDSCAPE_HEIGHT,
};
export const PORTRAIT_MAIN_SIZES = {
	width: PORTRAIT_HEIGHT * PORTRAIT_RATIO,
	height: PORTRAIT_HEIGHT,
};

export const HIGH_SYMBOLS = ['H1', 'H2', 'H3', 'H4', 'H5'];

export const INITIAL_SYMBOL_STATE: SymbolState = 'static';

const M_SIZE = 0.9;
const HIGH_SYMBOL_SIZE = 0.9;
const LOW_SYMBOL_SIZE = 0.9;
const SPECIAL_SYMBOL_SIZE = 0.9;

const SPIN_OPTIONS_SHARED = {
	reelFallInDelay: 80,
	reelPaddingMultiplierNormal: 1.25,
	reelPaddingMultiplierAnticipated: 18,
	reelFallOutDelay: 145,
};

export const SPIN_OPTIONS_DEFAULT = {
	...SPIN_OPTIONS_SHARED,
	symbolFallInSpeed: 3.5,
	symbolFallInInterval: 30,
	symbolFallInBounceSpeed: 0.15,
	symbolFallInBounceSizeMulti: 0.5,
	symbolFallOutSpeed: 3.5,
	symbolFallOutInterval: 20,
};

export const SPIN_OPTIONS_FAST = {
	...SPIN_OPTIONS_SHARED,
	symbolFallInSpeed: 7,
	symbolFallInInterval: 0,
	symbolFallInBounceSpeed: 0.3,
	symbolFallInBounceSizeMulti: 0.25,
	symbolFallOutSpeed: 7,
	symbolFallOutInterval: 0,
};

export const MOTION_BLUR_VELOCITY = 31;

export const zIndexes = {
	background: {
		backdrop: -3,
		normal: -2,
		feature: -1,
	},
};

const explosion = {
	type: 'spine',
	assetKey: 'explosion',
	animationName: 'explosion',
	sizeRatios: { width: 1, height: 1 },
};

const h1Static = { type: 'sprite', assetKey: 'h1 (1).png', sizeRatios: { width: 1, height: 1 } };
const h2Static = { type: 'sprite', assetKey: 'h2 (1).png', sizeRatios: { width: 1, height: 1 } };
const h3Static = { type: 'sprite', assetKey: 'h3 (1).png', sizeRatios: { width: 1, height: 1 } };
const h4Static = { type: 'sprite', assetKey: 'h4 (1).png', sizeRatios: { width: 1, height: 1 } };
const h5Static = { type: 'sprite', assetKey: 'h5 (1).png', sizeRatios: { width: 1, height: 1 } };
const l1Static = { type: 'sprite', assetKey: 'l1 (1).png', sizeRatios: { width: 1, height: 1 } };
const l2Static = { type: 'sprite', assetKey: 'l2 (1).png', sizeRatios: { width: 1, height: 1 } };
const l3Static = { type: 'sprite', assetKey: 'l3 (1).png', sizeRatios: { width: 1, height: 1 } };
const l4Static = { type: 'sprite', assetKey: 'l4 (1).png', sizeRatios: { width: 1, height: 1 } };
const sStatic = { type: 'sprite', assetKey: 's (1).png', sizeRatios: { width: 1.243, height: 1.243 } };
const wStatic = { type: 'sprite', assetKey: 'w.png', sizeRatios: { width: 1.12, height: 1.12 } };

const m2Static = {
	type: 'sprite',
	assetKey: 'm (1).png',
	sizeRatios: { width: 1, height: 1 },
};
const m4Static = {
	type: 'sprite',
	assetKey: 'm (1).png',
	sizeRatios: { width: 1, height: 1 },
};
const m5Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } };
const m7Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } };
const m10Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } };
const m15Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } };
const m25Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } }; 		
const m50Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } };
const m100Static = { type: 'sprite', assetKey: 'm (1).png', sizeRatios: { width: 1, height: 1 } }; 	

const mWin = {
	type: 'sprite',
	assetKeys: [
		'm (1).png',
		'm (2).png',
		'm (3).png',
		'm (4).png',
		'm (5).png',
		'm (6).png',
		'm (7).png',
		'm (8).png',
		'm (9).png',
		'm (10).png',
		'm (11).png',
		'm (12).png',
		'm (13).png',
		'm (14).png',
		'm (15).png',
		'm (16).png',
		'm (17).png',
		'm (18).png',
		'm (19).png',
		'm (20).png',
		'm (21).png',
		'm (22).png',
		'm (23).png',
		'm (24).png',
		'm (25).png',
		'm (26).png',
		'm (27).png',
		'm (28).png',
		'm (29).png',
		'm (30).png',
		'm (31).png',
		'm (32).png',
		'm (33).png',
		'm (34).png',
		'm (35).png',
		'm (36).png',
	],
	sizeRatios: { width: 1, height: 1 },
};



const wSizeRatios = { width: 1.5 * 0.9, height: SPECIAL_SYMBOL_SIZE * 1.15 };
const sSizeRatios = { width: 1.2, height: SPECIAL_SYMBOL_SIZE * 1.4 };

const backgroundLowStatic = {
	type: 'sprite',
	assetKey: 'm (1).png',
	sizeRatios: { width: M_SIZE, height: M_SIZE },
};
const backgroundMidStatic = {
	type: 'sprite',
	assetKey: 'm (1).png',
	sizeRatios: { width: M_SIZE, height: M_SIZE },
};
const backgroundHighStatic = {
	type: 'sprite',
	assetKey: 'm (1).png',
	sizeRatios: { width: M_SIZE, height: M_SIZE },
};

const backgroundLow = {
	explosion,
	win: backgroundLowStatic,
	postWinStatic: backgroundLowStatic,
	static: backgroundLowStatic,
	spin: backgroundLowStatic,
	land: backgroundLowStatic,
};

const backgroundMid = {
	explosion,
	win: backgroundMidStatic,
	postWinStatic: backgroundMidStatic,
	static: backgroundMidStatic,
	spin: backgroundMidStatic,
	land: backgroundMidStatic,
};

const backgroundHigh = {
	explosion,
	win: backgroundHighStatic,
	postWinStatic: backgroundHighStatic,
	static: backgroundHighStatic,
	spin: backgroundHighStatic,
	land: backgroundHighStatic,
};

export const SYMBOL_INFO_MAP = {
	H1: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'h1 (1).png',
				'h1 (2).png',
				'h1 (3).png',
				'h1 (4).png',
				'h1 (5).png',
				'h1 (6).png',
				'h1 (7).png',
				'h1 (8).png',
				'h1 (9).png',
				'h1 (10).png',
				'h1 (11).png',
				'h1 (12).png',
				'h1 (13).png',
				'h1 (14).png',
				'h1 (15).png',
				'h1 (16).png',
				'h1 (17).png',
				'h1 (18).png',
				'h1 (19).png',
				'h1 (20).png',
				'h1 (21).png',
				'h1 (22).png',
				'h1 (23).png',
				'h1 (24).png',
				'h1 (25).png',
				'h1 (26).png',
				'h1 (27).png',
				'h1 (28).png',
				'h1 (29).png',
				'h1 (30).png',
				'h1 (31).png',
				'h1 (32).png',
				'h1 (33).png',
				'h1 (34).png',
				'h1 (35).png',
				'h1 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: h1Static,
		static: h1Static,
		spin: h1Static,
		land: h1Static,
	},
	H2: {
		explosion,
			win: {
			type: 'sprite',
			assetKeys: [
				'h2 (1).png',
				'h2 (2).png',
				'h2 (3).png',
				'h2 (4).png',
				'h2 (5).png',
				'h2 (6).png',
				'h2 (7).png',
				'h2 (8).png',
				'h2 (9).png',
				'h2 (10).png',
				'h2 (11).png',
				'h2 (12).png',
				'h2 (13).png',
				'h2 (14).png',
				'h2 (15).png',
				'h2 (16).png',
				'h2 (17).png',
				'h2 (18).png',
				'h2 (19).png',
				'h2 (20).png',
				'h2 (21).png',
				'h2 (22).png',
				'h2 (23).png',
				'h2 (24).png',
				'h2 (25).png',
				'h2 (26).png',
				'h2 (27).png',
				'h2 (28).png',
				'h2 (29).png',
				'h2 (30).png',
				'h2 (31).png',
				'h2 (32).png',
				'h2 (33).png',
				'h2 (34).png',
				'h2 (35).png',
				'h2 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: h2Static,
		static: h2Static,
		spin: h2Static,
		land: h2Static,
	},
	H3: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'h3 (1).png',
				'h3 (2).png',
				'h3 (3).png',
				'h3 (4).png',
				'h3 (5).png',
				'h3 (6).png',
				'h3 (7).png',
				'h3 (8).png',
				'h3 (9).png',
				'h3 (10).png',
				'h3 (11).png',
				'h3 (12).png',
				'h3 (13).png',
				'h3 (14).png',
				'h3 (15).png',
				'h3 (16).png',
				'h3 (17).png',
				'h3 (18).png',
				'h3 (19).png',
				'h3 (20).png',
				'h3 (21).png',
				'h3 (22).png',
				'h3 (23).png',
				'h3 (24).png',
				'h3 (25).png',
				'h3 (26).png',
				'h3 (27).png',
				'h3 (28).png',
				'h3 (29).png',
				'h3 (30).png',
				'h3 (31).png',
				'h3 (32).png',
				'h3 (33).png',
				'h3 (34).png',
				'h3 (35).png',
				'h3 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: h3Static,
		static: h3Static,
		spin: h3Static,
		land: h3Static,
	},
	H4: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'h4 (1).png',
				'h4 (2).png',
				'h4 (3).png',
				'h4 (4).png',
				'h4 (5).png',
				'h4 (6).png',
				'h4 (7).png',
				'h4 (8).png',
				'h4 (9).png',
				'h4 (10).png',
				'h4 (11).png',
				'h4 (12).png',
				'h4 (13).png',
				'h4 (14).png',
				'h4 (15).png',
				'h4 (16).png',
				'h4 (17).png',
				'h4 (18).png',
				'h4 (19).png',
				'h4 (20).png',
				'h4 (21).png',
				'h4 (22).png',
				'h4 (23).png',
				'h4 (24).png',
				'h4 (25).png',
				'h4 (26).png',
				'h4 (27).png',
				'h4 (28).png',
				'h4 (29).png',
				'h4 (30).png',
				'h4 (31).png',
				'h4 (32).png',
				'h4 (33).png',
				'h4 (34).png',
				'h4 (35).png',
				'h4 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: h4Static,
		static: h4Static,
		spin: h4Static,
		land: h4Static,
	},
	H5: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'h5 (1).png',
				'h5 (2).png',
				'h5 (3).png',
				'h5 (4).png',
				'h5 (5).png',
				'h5 (6).png',
				'h5 (7).png',
				'h5 (8).png',
				'h5 (9).png',
				'h5 (10).png',
				'h5 (11).png',
				'h5 (12).png',
				'h5 (13).png',
				'h5 (14).png',
				'h5 (15).png',
				'h5 (16).png',
				'h5 (17).png',
				'h5 (18).png',
				'h5 (19).png',
				'h5 (20).png',
				'h5 (21).png',
				'h5 (22).png',
				'h5 (23).png',
				'h5 (24).png',
				'h5 (25).png',
				'h5 (26).png',
				'h5 (27).png',
				'h5 (28).png',
				'h5 (29).png',
				'h5 (30).png',
				'h5 (31).png',
				'h5 (32).png',
				'h5 (33).png',
				'h5 (34).png',
				'h5 (35).png',
				'h5 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: h5Static,
		static: h5Static,
		spin: h5Static,
		land: h5Static,
	},
	L1: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'l1 (1).png',
				'l1 (2).png',
				'l1 (3).png',
				'l1 (4).png',
				'l1 (5).png',
				'l1 (6).png',
				'l1 (7).png',
				'l1 (8).png',
				'l1 (9).png',
				'l1 (10).png',
				'l1 (11).png',
				'l1 (12).png',
				'l1 (13).png',
				'l1 (14).png',
				'l1 (15).png',
				'l1 (16).png',
				'l1 (17).png',
				'l1 (18).png',
				'l1 (19).png',
				'l1 (20).png',
				'l1 (21).png',
				'l1 (22).png',
				'l1 (23).png',
				'l1 (24).png',
				'l1 (25).png',
				'l1 (26).png',
				'l1 (27).png',
				'l1 (28).png',
				'l1 (29).png',
				'l1 (30).png',
				'l1 (31).png',
				'l1 (32).png',
				'l1 (33).png',
				'l1 (34).png',
				'l1 (35).png',
				'l1 (36).png',
			],
			sizeRatios: sSizeRatios,
		},	
		postWinStatic: l1Static,
		static: l1Static,
		spin: l1Static,
		land: l1Static,
	},
	L2: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'l2 (1).png',
				'l2 (2).png',
				'l2 (3).png',
				'l2 (4).png',
				'l2 (5).png',
				'l2 (6).png',
				'l2 (7).png',
				'l2 (8).png',
				'l2 (9).png',
				'l2 (10).png',
				'l2 (11).png',
				'l2 (12).png',
				'l2 (13).png',
				'l2 (14).png',
				'l2 (15).png',
				'l2 (16).png',
				'l2 (17).png',
				'l2 (18).png',
				'l2 (19).png',
				'l2 (20).png',
				'l2 (21).png',
				'l2 (22).png',
				'l2 (23).png',
				'l2 (24).png',
				'l2 (25).png',
				'l2 (26).png',
				'l2 (27).png',
				'l2 (28).png',
				'l2 (29).png',
				'l2 (30).png',
				'l2 (31).png',
				'l2 (32).png',
				'l2 (33).png',
				'l2 (34).png',
				'l2 (35).png',
				'l2 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: l2Static,
		static: l2Static,
		spin: l2Static,
		land: l2Static,
	},
	L3: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'l3 (1).png',
				'l3 (2).png',
				'l3 (3).png',
				'l3 (4).png',
				'l3 (5).png',
				'l3 (6).png',
				'l3 (7).png',
				'l3 (8).png',
				'l3 (9).png',
				'l3 (10).png',
				'l3 (11).png',
				'l3 (12).png',
				'l3 (13).png',
				'l3 (14).png',
				'l3 (15).png',
				'l3 (16).png',
				'l3 (17).png',
				'l3 (18).png',
				'l3 (19).png',
				'l3 (20).png',
				'l3 (21).png',
				'l3 (22).png',
				'l3 (23).png',
				'l3 (24).png',
				'l3 (25).png',
				'l3 (26).png',
				'l3 (27).png',
				'l3 (28).png',
				'l3 (29).png',
				'l3 (30).png',
				'l3 (31).png',
				'l3 (32).png',
				'l3 (33).png',
				'l3 (34).png',
				'l3 (35).png',
				'l3 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: l3Static,
		static: l3Static,
		spin: l3Static,
		land: l3Static,
	},
	L4: {
		explosion,
		win: {
			type: 'sprite',
			assetKeys: [
				'l4 (1).png',
				'l4 (2).png',
				'l4 (3).png',
				'l4 (4).png',
				'l4 (5).png',
				'l4 (6).png',
				'l4 (7).png',
				'l4 (8).png',
				'l4 (9).png',
				'l4 (10).png',
				'l4 (11).png',
				'l4 (12).png',
				'l4 (13).png',
				'l4 (14).png',
				'l4 (15).png',
				'l4 (16).png',
				'l4 (17).png',
				'l4 (18).png',
				'l4 (19).png',
				'l4 (20).png',
				'l4 (21).png',
				'l4 (22).png',
				'l4 (23).png',
				'l4 (24).png',
				'l4 (25).png',
				'l4 (26).png',
				'l4 (27).png',
				'l4 (28).png',
				'l4 (29).png',
				'l4 (30).png',
				'l4 (31).png',
				'l4 (32).png',
				'l4 (33).png',
				'l4 (34).png',
				'l4 (35).png',
				'l4 (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		postWinStatic: l4Static,
		static: l4Static,
		spin: l4Static,
		land: l4Static,
	},
	W: {
		explosion,
		postWinStatic: {
			type: 'sprite',
			assetKey: 'explodedW.png',
			sizeRatios: { width: 0.85, height: 0.85 },
		},
		static: wStatic,
		spin: wStatic,
		win: { type: 'spine', assetKey: 'W', animationName: 'wild_dynamite', sizeRatios: wSizeRatios },
		land: {
			type: 'spine',
			assetKey: 'W',
			animationName: 'wild_dynamite_land',
			sizeRatios: wSizeRatios,
		},
	},
	S: {
		explosion,
		postWinStatic: sStatic,
		static: sStatic,
		spin: sStatic,
		win: {
			type: 'sprite',
			assetKeys: [
				's (1).png',
				's (2).png',
				's (3).png',
				's (4).png',
				's (5).png',
				's (6).png',
				's (7).png',
				's (8).png',
				's (9).png',
				's (10).png',
				's (11).png',
				's (12).png',
				's (13).png',
				's (14).png',
				's (15).png',
				's (16).png',
				's (17).png',
				's (18).png',
				's (19).png',
				's (20).png',
				's (21).png',
				's (22).png',
				's (23).png',
				's (24).png',
				's (25).png',
				's (26).png',
				's (27).png',
				's (28).png',
				's (29).png',
				's (30).png',
				's (31).png',
				's (32).png',
				's (33).png',
				's (34).png',
				's (35).png',
				's (36).png',
			],
			sizeRatios: sSizeRatios,
		},
		land: sStatic,
	},
	M_2: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_4: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_5: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_7: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_10: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_15: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_25: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_50: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_100: {
		explosion,
		postWinStatic: m10Static,
		static: m10Static,
		spin: m10Static,
		win: mWin,
		land: m10Static,
	},
	M_TAKEN_2: backgroundLow,
	M_TAKEN_4: backgroundLow,
	M_TAKEN_5: backgroundMid,
	M_TAKEN_7: backgroundMid,
	M_TAKEN_10: backgroundHigh,
} as const;

export const MULTIPLIER_BACKGROUND_INFO_MAP = {
	M_2: backgroundLow,
	M_4: backgroundLow,
	M_5: backgroundMid,
	M_7: backgroundMid,
	M_10: backgroundHigh,
	M_15: backgroundHigh, // Use high background for debug
};

export const SCATTER_LAND_SOUND_MAP = {
	1: 'sfx_scatter_stop_1',
	2: 'sfx_scatter_stop_2',
	3: 'sfx_scatter_stop_3',
	4: 'sfx_scatter_stop_4',
	5: 'sfx_scatter_stop_5',
} as const;
